name = "analytics-api"
main = "src/index.ts"
compatibility_date = "2023-10-16"

# Node compatibility for certain imports
compatibility_flags = [ "nodejs_compat" ]

# Bindings to D1 database for future use
[[d1_databases]]
binding = "DB"
database_name = "visitor-db"
database_id = "73d10a53-6166-49e5-a4ee-963401d267fb"

[vars]
TELEGRAM_CHAT_ID = "620806780"
